apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fullstack-k8s-backend:dev
          ports:
            - containerPort: 9000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/newsletter"
